### ISSUE TITLE
TSConfig imports do not work in WebWorkers

### ISSUE THREAD

**Issue by darkevilmac** [aleclarson/vite-tsconfig-paths#46]
I'm trying to use WebWorkers with this plugin using the built in tooling provided by [Vite](https://vitejs.dev/guide/features.html#web-workers).

Unfortunately I get issues when the worker is invoked, it's unable to resolve any imports using the tsconfig file and will only work if I continue to use relative imports.

I've also tested this using the resolve alias feature in the Vite config and it worked as expected, so the issue is isolated to the plugin itself.

I've setup a stackblitz where you can see the issue directly, if there's any more info you need from me just let me know.

https://stackblitz.com/edit/vite-tsconfigpaths-webworker

**Comment by aleclarson** [comment]
what do the debug logs say?

```sh
DEBUG="vite-tsconfig-paths" vite
```

**Comment by darkevilmac** [comment]
Gave that a run in the stackblitz container, here's the output.

https://gist.github.com/darkevilmac/3214cc763f63c4bcca1b87566acd0878

**Comment by aleclarson** [comment]
Released in v3.4.1

Please help me boost my Github sponsor count for as little as $1 as a token of appreciation for this plugin 😏

**Comment by laurentpayot** [comment]
With web workers this is working fine in **dev** mode (using v3.4.1).

But if I try to **build** with a web worker I get:
```
DEBUG=vite-tsconfig-paths npx vite build
  vite-tsconfig-paths options: {
  projects: [ '/home/laurent/projects/myproject/tsconfig.json' ],
  extensions: [ '.ts', '.tsx', '.js', '.jsx', '.mjs' ]
} +0ms
  vite-tsconfig-paths config loaded: {
  configPath: '/home/laurent/projects/myproject/tsconfig.json',
  include: undefined,
  exclude: undefined,
  allowJs: undefined,
  baseUrl: '/home/laurent/projects/myproject/src',
  paths: {
    '~appInit': [ 'firebase/app/appInit' ],
    '~authInit': [ 'firebase/auth/authInit' ],
    '~firestoreInit': [ 'firebase/firestore/firestoreInit' ],
    '~storageInit': [ 'firebase/storage/storageInit' ]
  },
  outDir: undefined
} +9ms
  vite-tsconfig-paths compiled globs: {
  included: [ /^\.\/((?:[^/]*(?:\/|$))*)([^/]*)$/ ],
  excluded: [
    /^\.\/node_modules\/((?:[^/]*(?:\/|$))*)$/,
    /^\.\/bower_components\/((?:[^/]*(?:\/|$))*)$/,
    /^\.\/jspm_packages\/((?:[^/]*(?:\/|$))*)$/
  ]
} +1ms
vite v2.9.6 building for production...                                   12:33:43
✓ 5 modules transformed.                                                 12:33:44
✓ 9 modules transformed.                                                 12:33:44

 ERROR  [vite:worker] [vite]: Rollup failed to resolve import "~firestoreInit" from "src/firebase/firestore/Users.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
file: /home/laurent/projects/myproject/src/firebase/worker.ts?worker


 ERROR  error during build:                                              12:33:44
Error: [vite]: Rollup failed to resolve import "~firestoreInit" from "src/firebase/firestore/Users.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/laurent/projects/myproject/node_modules/vite/dist/node/chunks/dep-3397b401.js:41405:19)
    at onwarn (/home/laurent/projects/myproject/node_modules/vite/dist/node/chunks/dep-3397b401.js:60511:13)
    at Object.onwarn (/home/laurent/projects/myproject/node_modules/rollup/dist/shared/rollup.js:23184:13)
    at ModuleLoader.handleResolveId (/home/laurent/projects/myproject/node_modules/rollup/dist/shared/rollup.js:22474:26)
    at /home/laurent/projects/myproject/node_modules/rollup/dist/shared/rollup.js:22435:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

In my main.ts file I use 
```typescript
import FirebaseWorker from './firebase/worker?worker'

// ...

const firebaseWorker = new FirebaseWorker()
```

@aleclarson  Should this issue be reopened?

**Comment by laurentpayot** [comment]
PS: By the way [tsconfig-paths just bumped to v4.0](https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md) ...

**Comment by laurentpayot** [comment]
I just deleted my previous comment about the build issue. I forgot to add the plugin in the vite `worker` options :man_facepalming: 
Thanks @aleclarson :+1:
