### ISSUE TITLE
Recrawl-sync error on local build error with docker

### ISSUE THREAD

**Issue by tomimarkus991** [aleclarson/vite-tsconfig-paths#55]
```
#13 0.783 > tsc && vite build
#13 0.783
#13 17.00 error during build:
#13 17.00 Error: ELOOP: too many symbolic links encountered, stat '//proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/proc/1/cwd/dev/fd/0'
#13 17.00     at Object.statSync (node:fs:1538:3)
#13 17.00     at Object.stat (/node_modules/recrawl-sync/lib/fs.js:10:22)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:55:31)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 17.00     at crawl (/node_modules/recrawl-sync/lib/recrawl.js:70:29)
#13 ERROR: executor failed running [/bin/sh -c npm run build]: exit code: 1
------
 > [build-stage 5/5] RUN npm run build:
------
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
```

Im getting this when building locally with docker

**Comment by ignatevdev** [comment]
Turned out the problem was that I was building the app inside the container's root folder.

Adding WORKDIR /app have solved the issue

**Comment by aleclarson** [comment]
Please clear your lockfile and confirm if `recrawl-sync@2.2.3` fixed this, thanks!
