### ISSUE TITLE
v4.0.0-alpha mega thread

### ISSUE THREAD

**Issue by aleclarson** [aleclarson/vite-tsconfig-paths#77]
```
pnpm i vite-tsconfig-paths@next
```

## Introducing v4.0.0 (alpha)

- **refactor: stop using tsconfig-paths package**
    It is better to let Vite handle all of the resolving, so that this plugin 
can be only responsible for the path mapping.
    
    At the same time, I am also adding the `tsconfck` package, which 
handles the loading of tsconfig.json files for us. This package is also 
used in Vite core (we should have Vite expose it in the future, to
 avoid the duplication).
    
    The `tsconfig-paths` package was previously responsible for config 
loading and much of the path resolving logic, but now we can ditch 
it! I'm also ditching the `recrawl-sync` package, which was used for 
crawling the filesystem in search of tsconfig.json files.

Fixes #54
Closes #73
Probably fixes #63
Probably fixes #68
Probably fixes #71

## Bugs down here 👇 

I don't expect there to be bugs, but we don't currently have an extensive test suite, so it's possible. If you find any, let me know and (if you're feeling extra generous) open a PR with a reproduction in the `./demo` folder.

**Comment by aleclarson** [comment]
If anyone wants to help update the test suite for v4, please see #81.

**Comment by aniravi24** [comment]
I use an NX monorepo setup and I'm unable to get the build to work with v4, but am able to get it to work with v3. Some imports in my project are not being resolved correctly - I have a project that references one of my libraries, and one of the libraries references another library. When a library references another library, the import doesn't seem to work correctly.

**Comment by DreierF** [comment]
I'm running into the same issue of getting `Rollup failed to resolve import` errors after the update to 4.0.0. It seems to happen when there is no `include` field given in a setup that uses project references. I have created a minimal reproducible example here: 
[vite-tsconfig-paths-resolve-repro.zip](https://github.com/aleclarson/vite-tsconfig-paths/files/10173633/vite-tsconfig-paths-resolve-repro.zip)

**Comment by devatrox** [comment]
I have the same issue. With 4.0.0 it cannot resolve anything that sits in the src folder, which I'm referencing like this 
`import RuntimeProvider from "components/RuntimeProvider";`

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "strictNullChecks": true,
    "strictFunctionTypes": false,
    "jsx": "react-jsx",
    "jsxImportSource": "theme-ui",
    "baseUrl": "src"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```
tsconfig.node.json
```
{
  "compilerOptions": {
    "composite": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
```
vite.config.ts
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
import svgrPlugin from "vite-plugin-svgr";

export default defineConfig({
  base: "/somepath/",
  esbuild: { jsx: "automatic" },
  build: {
    outDir: "build",
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        manualChunks: {
          vendor_react: ["react", "react-dom"],
          vendor_mqtt: ["precompiled-mqtt", "mqtt"],
          vendor_themeui: [
            "@emotion/react",
            "@theme-ui/color",
            "@theme-ui/css",
            "@theme-ui/mdx",
            "@theme-ui/presets",
            "@theme-ui/style-guide",
            "theme-ui",
          ],
          vendor_datefns: ["date-fns"],
        },
      },
    },
  },
  plugins: [
    react(),
    tsconfigPaths(),
    svgrPlugin({
      svgrOptions: {
        icon: true,
      },
    }),
  ],
});

```

**Comment by CHR-onicles** [comment]
Same issue as @devatrox, fails to resolve imports from `src` with v4.0

**Comment by mssngr** [comment]
It seems that even when `projects` or `root` is specified, `vite-tsconfig-paths` tries to use the `tsconfig.node.json` from Vite instead of the `tsconfig.json`.

```
  vite-tsconfig-paths projects: [ '/Users/gkonkle/dev/hummingbird/ui/tsconfig.json' ] +1ms
  vite-tsconfig-paths config loaded: {
  configPath: '/Users/gkonkle/dev/hummingbird/ui/tsconfig.node.json',
```

**Comment by CHR-onicles** [comment]
> Seems there were two bugs. Please try v4.0.1
> 
> * A tsconfig file with `references` array is now used again (unless the `files` property is explicitly an empty array)
> * The `include`/`exclude` patterns are compiled correctly again

The error persists on v4.0.1, still unable to resolve imports from `src`

**Comment by aleclarson** [comment]
@CHR-onicles Can't reproduce. I tested that specifically before & after publishing v4.0.1

**Comment by aniravi24** [comment]
@aleclarson sorry for the delay, looks like everyone else got to this quickly and discovered the issue (thank you!) I can also confirm 4.0.1 fixed the specific issue I was having.

**Comment by DreierF** [comment]
There still seem to be issues under Windows using 4.0.1. A few of my colleges reported the following crash while it works fine under UNIX base systems.

```
error when starting dev server:
TSConfckParseError: failed to resolve "extends":"../tsconfig-base.json" in C:\project\out\test\resources\tsconfig.json
    at resolveExtends (C:\project\node_modules\.pnpm\tsconfck@2.0.1_typescript@4.9.3\node_modules\tsconfck\dist\index.cjs:491:9)
    at parseExtends (C:\project\node_modules\.pnpm\tsconfck@2.0.1_typescript@4.9.3\node_modules\tsconfck\dist\index.cjs:464:34)
    at Object.parse (C:\project\node_modules\.pnpm\tsconfck@2.0.1_typescript@4.9.3\node_modules\tsconfck\dist\index.cjs:415:24)
    at async Promise.all (index 2)
    at async configResolved (C:\project\node_modules\.pnpm\vite-tsconfig-paths@4.0.1_sqshdgy4e5w27wzvykvnubcgki\node_modules\vite-tsconfig-paths\dist\index.js:124:9)
    at async Promise.all (index 1)
    at async resolveConfig (file:///C:/project/node_modules/.pnpm/vite@3.2.5_pj4jucelx6r6jy43v33fk7tcnu/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:62878:5)
    at async createServer (file:///C:/project/node_modules/.pnpm/vite@3.2.5_pj4jucelx6r6jy43v33fk7tcnu/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:61943:20)
    at async CAC.<anonymous> (file:///C:/project/node_modules/.pnpm/vite@3.2.5_pj4jucelx6r6jy43v33fk7tcnu/node_modules/vite/dist/node/cli.js:707:24)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mandarini** [comment]
@aniravi24 @DreierF for Nx:

* To work with `4.0.0` you can remove the `projects: ['tsconfig.base.json']` from the plugin in your `vite.config.ts` files
* To work with `4.0.1` you still need the `projects` array

I put in a [PR](https://github.com/aleclarson/vite-tsconfig-paths/pull/84) to address that. Other than this, it should work as expected.

**Comment by dospolov** [comment]
4.0.0 and 4.0.1 doesn't work on Windows for me. All 3.6.* worked fine.
![image](https://user-images.githubusercontent.com/670682/206708264-1dc7cfa5-cf4a-4c80-853b-426b4a266de0.png)
![image](https://user-images.githubusercontent.com/670682/206708292-4138f6d9-55a1-445c-9273-d25df4ad36c5.png)

**Comment by Ludea** [comment]
since update to vite 4.0.1 and vite-tesconfig-paths to 4.0.2, get `Error: [vite]: Rollup failed to resolve import "App" from "/home/runner/work/tauri-mobile/tauri-mobile/src/main.tsx". `
It happen on Ubuntu 22.04

**Comment by memark** [comment]
It would be great if the Releases page were updated with information about this new major version
https://github.com/aleclarson/vite-tsconfig-paths/releases

**Comment by alonando** [comment]
Seeing the same issue. Stuck with version 3 of vite and vite-tsconfig-paths.
Any known workarounds?

**Comment by marlosirapuan** [comment]
This error occurs only in win. In mac it works. Just rollback to vite-tsconfig-path 3.6.0 that will work (with vite 4.0.2 too)

**Comment by aleclarson** [comment]
Please try v4.0.3 if you're on Windows.

**Comment by aleclarson** [comment]
Please try v4.0.3 if you're on Windows. Thanks to @joshwooding

**Comment by alonando** [comment]
v4.0.3 is working on Windows with latest vite. Thanks @aleclarson & @joshwooding!

**Comment by ahnpnl** [comment]
Hi, it'd be nice if GH release page is up-to-date with release tags as well as changelog is mentioned somewhere.

**Comment by burtek** [comment]
Would it be possible to have this work also with `vitest.mock`? Right now the alaises from `compilerOptions.paths` don't work
